### ISSUE TITLE
建议删除 Data/gae_proxt/ 里的证书

### ISSUE THREAD

**Issue by Cat7373** [yeahwu/chrome-xx#3]
每个用户都自动生成一个新的证书可以防止中间人攻击。

**Comment by yeahwu** [comment]
好主意。但是这个项目已经暂停了！哎
Cat73 <notifications@github.com>于2015年12月11日 周五19:12写道：

**Comment by Cat7373** [comment]
@yeahwu 
不知道 data/gae_proxy/certs/ 里的文件会不会影响使用- -
比如证书错误神马的- -

**Comment by yeahwu** [comment]
不会，证书自动导入。chrome不会有证书问题。

Cat73 <notifications@github.com>于2015年12月12日 周六22:01写道：
