### ISSUE TITLE
SwitchyOmega插件可能损坏？

### ISSUE THREAD

**Issue by zhaoweiwang** [yeahwu/chrome-xx#5]
今天给别人装的时候不能上翻墙，看看是什么原因？我看了下扩展程序里的omega，提示可能损坏

**Comment by yeahwu** [comment]
github的原因，你到dropbox里下载。
Mako Wan <notifications@github.com>于2015年12月22日 周二14:27写道：

**Comment by yeahwu** [comment]
@zhaoweiwang  这是由于github自动解压缩导致的，点击dropbox下载，或者重新下载即可解决。

**Comment by zhaoweiwang** [comment]
@yeahwu 好的，明天试一下，谢谢仓主及时的回复~圣诞节快乐
